import { GoogleGenerativeAI } from '@google/generative-ai';
import { LLMProvider } from './llm.interface.js';

export class GeminiAdapter extends LLMProvider {
  constructor() {
    super();
    this.genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY || 'mock-key');
    this.model = 'gemini-1.5-flash';
    this.isMock = !process.env.GEMINI_API_KEY;
  }

  async generateText(prompt, options = {}) {
    if (this.isMock) {
      return this._mockResponse(prompt);
    }

    try {
      const model = this.genAI.getGenerativeModel({ model: options.model || this.model });
      const result = await model.generateContent(prompt);
      const response = await result.response;
      return response.text();
    } catch (error) {
      console.error('Gemini API Error:', error);
      throw new Error('Failed to generate response from Gemini');
    }
  }

  async generateStructured(prompt, schemaName) {
    if (this.isMock) {
      return this._mockStructuredResponse(schemaName);
    }

    try {
      const model = this.genAI.getGenerativeModel({ 
        model: 'gemini-1.5-flash',
        generationConfig: {
          responseMimeType: "application/json",
        }
      });
      
      const result = await model.generateContent(prompt);
      const response = await result.response;
      return JSON.parse(response.text());
    } catch (error) {
      console.error('Gemini API Error:', error);
      throw new Error('Failed to generate structured response from Gemini');
    }
  }

  _mockResponse(prompt) {
    return "This is a mock AI response since no API key was provided. In production, this would be generated by Google Gemini.";
  }

  _mockStructuredResponse(schemaName) {
    return {
      success: true,
      message: "Mock structured response from Gemini adapter",
      mockData: true
    };
  }
}
