import { OpenAI } from 'openai';
import { LLMProvider } from './llm.interface.js';

export class OpenAIAdapter extends LLMProvider {
  constructor() {
    super();
    this.client = new OpenAI({
      apiKey: process.env.OPENAI_API_KEY || 'mock-key',
    });
    this.model = 'gpt-4o-mini'; // default model
    this.isMock = !process.env.OPENAI_API_KEY;
  }

  async generateText(prompt, options = {}) {
    if (this.isMock) {
      return this._mockResponse(prompt);
    }

    try {
      const response = await this.client.chat.completions.create({
        model: options.model || this.model,
        messages: [{ role: 'user', content: prompt }],
        temperature: options.temperature || 0.7,
        max_tokens: options.maxTokens,
      });

      return response.choices[0].message.content;
    } catch (error) {
      console.error('OpenAI API Error:', error);
      throw new Error('Failed to generate response from OpenAI');
    }
  }

  async generateStructured(prompt, schemaName) {
    if (this.isMock) {
      return this._mockStructuredResponse(schemaName);
    }

    try {
      const response = await this.client.chat.completions.create({
        model: 'gpt-4o-2024-08-06', // Model that supports structured outputs well
        messages: [
          { 
            role: 'system', 
            content: 'You are a helpful assistant that outputs strictly valid JSON.' 
          },
          { role: 'user', content: prompt }
        ],
        response_format: { type: "json_object" },
        temperature: 0.2,
      });

      return JSON.parse(response.choices[0].message.content);
    } catch (error) {
      console.error('OpenAI API Error:', error);
      throw new Error('Failed to generate structured response from OpenAI');
    }
  }

  _mockResponse(prompt) {
    return "This is a mock AI response since no API key was provided. In production, this would be generated by OpenAI.";
  }

  _mockStructuredResponse(schemaName) {
    // Provide generic mock structures based on request
    return {
      success: true,
      message: "Mock structured response",
      mockData: true
    };
  }
}
